-- Add new values to ListingStatus enum
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'AWAITING_PAYMENT';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'PENDING_REVIEW';
ALTER TYPE "ListingStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
